apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-app
  labels:
    app: event-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service-app
  template:
    metadata:
      labels:
        app: event-service-app
    spec:
      containers:
        - name: event-service-app
          image: ghcr.io/hangbuddy/hb-event-service:master
          imagePullPolicy: Always
      imagePullSecrets:
        - name: hangbuddy
---
apiVersion: v1
kind: Service
metadata:
  name: event-service-svc
spec:
  selector:
    app: event-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80