kubectl delete deployment events-depl
kubectl delete deployment users-depl
kubectl delete deployment mssql-depl
kubectl delete svc --all
kubectl apply -f local-pvc.yaml
kubectl apply -f mssql-plat-depl.yaml
kubectl apply -f users-depl.yaml
kubectl apply -f events-depl.yaml
kubectl apply -f hangbuddy-np-srv.yaml