apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: ghcr.io/hangbuddy/hb-user-service:master
          imagePullPolicy: Always
      imagePullSecrets:
        - name: hangbuddy
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80